<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <EmbeddedResource Include="Assets\lua\adb.lua" LogicalName="BotBuilder.Core.Assets.lua.adb.lua" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AdbCore\AdbCore.csproj" />
    <ProjectReference Include="..\AdbUi.Theme\AdbUi.Theme.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BotBuilder.Core</RootNamespace>
  </PropertyGroup>

</Project>
